Update boardwalk install process (closes #21)
ucsc-cgp/cgp-deployment pull request #22
Opened 2018-05-15 21:15 UTC by natanlao

2018-05-15 21:20 UTC, coverbeck requested changes

2018-05-15 21:20 UTC, coverbeck commented on boardwalk/README.md
> +To make deployment during development faster, the `install_bootstrap` script will clone [cgp-dashboard](https://github.com/DataBiosphere/cgp-dashboard), [cgp-dashboard-service](https://github.com/Dat
We don't use dcc-metadata-indexer in feature/commons branch. Looks like I hadn't cleaned removed the reference to it.

We will need to clone DataBiosphere/boardwalk

2018-05-15 21:20 UTC, coverbeck commented on install_bootstrap
> +        check_for_repo https://github.com/BD2KGenomics/dcc-metadata-indexer.git dcc-metadata-indexer
See previous comment about metadata indexer and boardwalk.

2018-05-15 23:05 UTC, coverbeck commented
These changes look good, but, I just noticed there are a bunch of other things in the README that need to be fixed as well. For example, references to metadata-indexer, instructions to type random strings...

Do you want to keep this PR scoped to this change and handle the rest in other PRs, or do you want to try to get it all in good?

2018-05-16 19:44 UTC, natanlao commented
If it's all the same to you, I'll keep this PR scoped and submit another PR
in the coming days?

On Tue, May 15, 2018 at 4:05 PM Charles Overbeck <notifications@github.com>
wrote:

> These changes look good, but, I just noticed there are a bunch of other
> things in the README that need to be fixed as well. For example, references
> to metadata-indexer, instructions to type random strings...
>
> Do you want to keep this PR scoped to this change and handle the rest in
> other PRs, or do you want to try to get it all in good?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DataBiosphere/cgp-deployment/pull/22#issuecomment-389341870>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWJOIq8SvKa00QhbgIe9t88yq7srwJc9ks5ty18ngaJpZM4UASTC>
> .
>

2018-05-16 20:12 UTC, coverbeck approved these changes
Agreed, tackle the other points in another PR.

LGTM.

2018-05-17 22:07 UTC, merged